services:
  postgres-test:
    image: postgres:15
    container_name: postgres_db_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres_db_test
    ports:
      - "5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
